# Default values for python.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 16
image:
  pullPolicy: IfNotPresent
service:
  name: python
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 1
    memory: 1G
  requests:
    cpu: 1
    memory: 1G
ingress:
  enabled: false
